
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_BTNS_4BITS_DEVICE_ID,
		XPAR_BTNS_4BITS_BASEADDR,
		XPAR_BTNS_4BITS_INTERRUPT_PRESENT,
		XPAR_BTNS_4BITS_IS_DUAL
	},
	{
		XPAR_SWS_4BITS_DEVICE_ID,
		XPAR_SWS_4BITS_BASEADDR,
		XPAR_SWS_4BITS_INTERRUPT_PRESENT,
		XPAR_SWS_4BITS_IS_DUAL
	}
};


